services:
  - type: web
    name: yt-to-instagram
    runtime: python
    buildCommand: apt-get update -qq && apt-get install -y -qq ffmpeg && pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --worker-class gevent --workers 2 --timeout 660 --keep-alive 660
    envVars:
      - key: INSTAGRAM_ACCESS_TOKEN
        sync: false          # You'll paste this in Render dashboard
      - key: INSTAGRAM_USER_ID
        sync: false          # You'll paste this in Render dashboard
